module.exports = {
    apps: [
        {
            instances: 4,
            name: 'queue-workers',
            script: 'artisan',
            args: 'queue:work --sleep=3 --tries=2 --timeout=240',
            interpreter_args: '-c "umask 0002 && exec php artisan queue:work --queue=realtime,high,default --sleep=3 --tries=2 --timeout=60"',
            cwd: './',
            error_file: './storage/logs/pm2/queue-workers/pm2-error.log',
            out_file: './storage/logs/pm2/queue-workers/pm2-out.log',
            cron_restart: '0 0 * * *',
            stop_exit_codes: [0],
            restart_delay: 1000,
            autorestart: true,
            merge_logs: true,
            watch: false,
            exec_mode: 'fork',
            interpreter: '/bin/bash',
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            instances: 1,
            name: 'reverb',
            script: 'artisan',
            args: 'reverb:start',
            interpreter_args:
                '-c "umask 0002 && exec php artisan reverb:start --host=${REVERB_SERVER_HOST:-0.0.0.0} --port=${REVERB_SERVER_PORT:-8080} --hostname=${REVERB_HOST:-127.0.0.1} --no-interaction"',
            cwd: './',
            error_file: './storage/logs/pm2/reverb/pm2-error.log',
            out_file: './storage/logs/pm2/reverb/pm2-out.log',
            cron_restart: '0 0 * * *',
            stop_exit_codes: [0],
            restart_delay: 1000,
            autorestart: true,
            merge_logs: true,
            watch: false,
            exec_mode: 'fork',
            interpreter: '/bin/bash',
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            instances: 2,
            name: 'scheduler',
            script: 'artisan',
            args: 'schedule:work',
            interpreter_args: '-c "umask 0002 && exec php artisan schedule:work"',
            cwd: './',
            error_file: './storage/logs/pm2/scheduler/pm2-error.log',
            out_file: './storage/logs/pm2/scheduler/pm2-out.log',
            cron_restart: '0 0 * * *',
            stop_exit_codes: [0],
            restart_delay: 1000,
            autorestart: true,
            merge_logs: true,
            watch: false,
            exec_mode: 'fork',
            interpreter: '/bin/bash',
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
            },
        },
    ],
};
