/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Deferred: typeof import('@inertiajs/vue3').Deferred
  const EffectScope: typeof import('vue').EffectScope
  const Method: typeof import('@inertiajs/core').Method
  const RealtimeChannelParameter: typeof import('../lib/realtime/channels').RealtimeChannelParameter
  const Ziggy: typeof import('ziggy-js').Ziggy
  const apiRequest: typeof import('../composables/useApiClient').apiRequest
  const appRoutes: typeof import('@/routes/app').default
  const authRoutes: typeof import('@/routes/auth').default
  const bindGlobalRouteHelper: typeof import('../utils/ziggy').bindGlobalRouteHelper
  const buildDashboardBreadcrumbs: typeof import('@/config/breadcrumbs').buildDashboardBreadcrumbs
  const buildSettingsAppearanceBreadcrumbs: typeof import('@/config/breadcrumbs').buildSettingsAppearanceBreadcrumbs
  const buildSettingsPasswordBreadcrumbs: typeof import('@/config/breadcrumbs').buildSettingsPasswordBreadcrumbs
  const buildSettingsProfileBreadcrumbs: typeof import('@/config/breadcrumbs').buildSettingsProfileBreadcrumbs
  const buildUsersBreadcrumbs: typeof import('@/config/breadcrumbs').buildUsersBreadcrumbs
  const clearApiQueryCache: typeof import('../composables/useApiQuery').clearApiQueryCache
  const cn: typeof import('../lib/utils').cn
  const computed: typeof import('vue').computed
  const configureRealtime: typeof import('../lib/realtime/config').configureRealtime
  const createApp: typeof import('vue').createApp
  const createRealtimeConfig: typeof import('../lib/realtime/config').createRealtimeConfig
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineFormContract: typeof import('../lib/forms').defineFormContract
  const disconnectRealtime: typeof import('../lib/realtime/config').disconnectRealtime
  const effectScope: typeof import('vue').effectScope
  const getApiQueryCacheData: typeof import('../composables/useApiQuery').getApiQueryCacheData
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getEnumOptions: typeof import('../lib/utils').getEnumOptions
  const getInitials: typeof import('../composables/useInitials').getInitials
  const getMonths: typeof import('../lib/utils').getMonths
  const getRealtimeClient: typeof import('../lib/realtime/config').getRealtimeClient
  const getRealtimeSocketId: typeof import('../lib/realtime/config').getRealtimeSocketId
  const getYears: typeof import('../lib/utils').getYears
  const h: typeof import('vue').h
  const initializeTheme: typeof import('../composables/useAppearance').initializeTheme
  const inject: typeof import('vue').inject
  const invalidateApiQueryCache: typeof import('../composables/useApiQuery').invalidateApiQueryCache
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRealtimeConfigured: typeof import('../lib/realtime/config').isRealtimeConfigured
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapInertiaFormErrors: typeof import('../lib/forms').mapInertiaFormErrors
  const markRaw: typeof import('vue').markRaw
  const marketingRoutes: typeof import('@/routes/marketing').default
  const nextTick: typeof import('vue').nextTick
  const normalizeApiError: typeof import('../composables/useApiClient').normalizeApiError
  const omitUndefinedProps: typeof import('../lib/utils').omitUndefinedProps
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parameters: typeof import('../lib/realtime/channels').parameters
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveRealtimeChannel: typeof import('../lib/realtime/channels').resolveRealtimeChannel
  const resolveServerTableInitialQuery: typeof import('../composables/useServerDataTable').resolveServerTableInitialQuery
  const router: typeof import('@inertiajs/vue3').router
  const setApiQueryCacheData: typeof import('../composables/useApiQuery').setApiQueryCacheData
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toInertiaRouteDefinition: typeof import('../utils/route').toInertiaRouteDefinition
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toZiggyVueConfig: typeof import('../utils/ziggy').toZiggyVueConfig
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateTheme: typeof import('../composables/useAppearance').updateTheme
  const useApiMutation: typeof import('../composables/useApiQuery').useApiMutation
  const useApiQuery: typeof import('../composables/useApiQuery').useApiQuery
  const useAppPage: typeof import('../composables/useAppPage').useAppPage
  const useAppearance: typeof import('../composables/useAppearance').useAppearance
  const useAttrs: typeof import('vue').useAttrs
  const useAuthUser: typeof import('../composables/useAppPage').useAuthUser
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useFlashToasts: typeof import('../composables/useFlashToasts').useFlashToasts
  const useForm: typeof import('@inertiajs/vue3').useForm
  const useId: typeof import('vue').useId
  const useInitials: typeof import('../composables/useInitials').useInitials
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useNavigation: typeof import('../composables/useNavigation').useNavigation
  const usePage: typeof import('@inertiajs/vue3').usePage
  const usePoll: typeof import('@inertiajs/vue3').usePoll
  const useRealtimeConnection: typeof import('../composables/useRealtimeConnection').useRealtimeConnection
  const useRealtimeEvent: typeof import('../composables/useRealtime').useRealtimeEvent
  const useRealtimeModel: typeof import('../composables/useRealtime').useRealtimeModel
  const useRealtimeNotification: typeof import('../composables/useRealtime').useRealtimeNotification
  const useRealtimePresence: typeof import('../composables/useRealtime').useRealtimePresence
  const useRemember: typeof import('@inertiajs/vue3').useRemember
  const useResourceForm: typeof import('../composables/useResourceForm').useResourceForm
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSchemaResourceForm: typeof import('../composables/useSchemaResourceForm').useSchemaResourceForm
  const useServerDataTable: typeof import('../composables/useServerDataTable').useServerDataTable
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToast: typeof import('../composables/useToast').useToast
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ApiError, ApiRequestMethod, ApiRequestOptions, ApiResponseParser } from '../composables/useApiClient'
  import('../composables/useApiClient')
  // @ts-ignore
  export type { ApiCacheKey } from '../composables/useApiQuery'
  import('../composables/useApiQuery')
  // @ts-ignore
  export type { Appearance } from '../composables/useAppearance'
  import('../composables/useAppearance')
  // @ts-ignore
  export type { RealtimeCacheKey, RealtimeNotification } from '../composables/useRealtime'
  import('../composables/useRealtime')
  // @ts-ignore
  export type { RealtimeConnectionStatus } from '../composables/useRealtimeConnection'
  import('../composables/useRealtimeConnection')
  // @ts-ignore
  export type { ResourceSubmitOptions } from '../composables/useResourceForm'
  import('../composables/useResourceForm')
  // @ts-ignore
  export type { FormErrorMap, FormContract } from '../lib/forms'
  import('../lib/forms')
  // @ts-ignore
  export type { RealtimeAuthMode, RealtimeAuthStrategy, ConfigureRealtimeOptions } from '../lib/realtime/config'
  import('../lib/realtime/config')
  // @ts-ignore
  export type { InertiaMethod, InertiaRouteDefinition } from '../utils/route'
  import('../utils/route')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly Deferred: UnwrapRef<typeof import('@inertiajs/vue3')['Deferred']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Method: UnwrapRef<typeof import('@inertiajs/core')['Method']>
    readonly RealtimeChannelParameter: UnwrapRef<typeof import('../lib/realtime/channels')['RealtimeChannelParameter']>
    readonly Ziggy: UnwrapRef<typeof import('ziggy-js')['Ziggy']>
    readonly apiRequest: UnwrapRef<typeof import('../composables/useApiClient')['apiRequest']>
    readonly appRoutes: UnwrapRef<typeof import('@/routes/app')['default']>
    readonly authRoutes: UnwrapRef<typeof import('@/routes/auth')['default']>
    readonly bindGlobalRouteHelper: UnwrapRef<typeof import('../utils/ziggy')['bindGlobalRouteHelper']>
    readonly buildDashboardBreadcrumbs: UnwrapRef<typeof import('@/config/breadcrumbs')['buildDashboardBreadcrumbs']>
    readonly buildSettingsAppearanceBreadcrumbs: UnwrapRef<typeof import('@/config/breadcrumbs')['buildSettingsAppearanceBreadcrumbs']>
    readonly buildSettingsPasswordBreadcrumbs: UnwrapRef<typeof import('@/config/breadcrumbs')['buildSettingsPasswordBreadcrumbs']>
    readonly buildSettingsProfileBreadcrumbs: UnwrapRef<typeof import('@/config/breadcrumbs')['buildSettingsProfileBreadcrumbs']>
    readonly buildUsersBreadcrumbs: UnwrapRef<typeof import('@/config/breadcrumbs')['buildUsersBreadcrumbs']>
    readonly clearApiQueryCache: UnwrapRef<typeof import('../composables/useApiQuery')['clearApiQueryCache']>
    readonly cn: UnwrapRef<typeof import('../lib/utils')['cn']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly configureRealtime: UnwrapRef<typeof import('../lib/realtime/config')['configureRealtime']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createRealtimeConfig: UnwrapRef<typeof import('../lib/realtime/config')['createRealtimeConfig']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineFormContract: UnwrapRef<typeof import('../lib/forms')['defineFormContract']>
    readonly disconnectRealtime: UnwrapRef<typeof import('../lib/realtime/config')['disconnectRealtime']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getApiQueryCacheData: UnwrapRef<typeof import('../composables/useApiQuery')['getApiQueryCacheData']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getEnumOptions: UnwrapRef<typeof import('../lib/utils')['getEnumOptions']>
    readonly getInitials: UnwrapRef<typeof import('../composables/useInitials')['getInitials']>
    readonly getMonths: UnwrapRef<typeof import('../lib/utils')['getMonths']>
    readonly getRealtimeClient: UnwrapRef<typeof import('../lib/realtime/config')['getRealtimeClient']>
    readonly getRealtimeSocketId: UnwrapRef<typeof import('../lib/realtime/config')['getRealtimeSocketId']>
    readonly getYears: UnwrapRef<typeof import('../lib/utils')['getYears']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly initializeTheme: UnwrapRef<typeof import('../composables/useAppearance')['initializeTheme']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly invalidateApiQueryCache: UnwrapRef<typeof import('../composables/useApiQuery')['invalidateApiQueryCache']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRealtimeConfigured: UnwrapRef<typeof import('../lib/realtime/config')['isRealtimeConfigured']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly mapInertiaFormErrors: UnwrapRef<typeof import('../lib/forms')['mapInertiaFormErrors']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly marketingRoutes: UnwrapRef<typeof import('@/routes/marketing')['default']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeApiError: UnwrapRef<typeof import('../composables/useApiClient')['normalizeApiError']>
    readonly omitUndefinedProps: UnwrapRef<typeof import('../lib/utils')['omitUndefinedProps']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parameters: UnwrapRef<typeof import('../lib/realtime/channels')['parameters']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveRealtimeChannel: UnwrapRef<typeof import('../lib/realtime/channels')['resolveRealtimeChannel']>
    readonly resolveServerTableInitialQuery: UnwrapRef<typeof import('../composables/useServerDataTable')['resolveServerTableInitialQuery']>
    readonly router: UnwrapRef<typeof import('@inertiajs/vue3')['router']>
    readonly setApiQueryCacheData: UnwrapRef<typeof import('../composables/useApiQuery')['setApiQueryCacheData']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toInertiaRouteDefinition: UnwrapRef<typeof import('../utils/route')['toInertiaRouteDefinition']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toZiggyVueConfig: UnwrapRef<typeof import('../utils/ziggy')['toZiggyVueConfig']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateTheme: UnwrapRef<typeof import('../composables/useAppearance')['updateTheme']>
    readonly useApiMutation: UnwrapRef<typeof import('../composables/useApiQuery')['useApiMutation']>
    readonly useApiQuery: UnwrapRef<typeof import('../composables/useApiQuery')['useApiQuery']>
    readonly useAppPage: UnwrapRef<typeof import('../composables/useAppPage')['useAppPage']>
    readonly useAppearance: UnwrapRef<typeof import('../composables/useAppearance')['useAppearance']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthUser: UnwrapRef<typeof import('../composables/useAppPage')['useAuthUser']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useFlashToasts: UnwrapRef<typeof import('../composables/useFlashToasts')['useFlashToasts']>
    readonly useForm: UnwrapRef<typeof import('@inertiajs/vue3')['useForm']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useInitials: UnwrapRef<typeof import('../composables/useInitials')['useInitials']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNavigation: UnwrapRef<typeof import('../composables/useNavigation')['useNavigation']>
    readonly usePage: UnwrapRef<typeof import('@inertiajs/vue3')['usePage']>
    readonly usePoll: UnwrapRef<typeof import('@inertiajs/vue3')['usePoll']>
    readonly useRealtimeConnection: UnwrapRef<typeof import('../composables/useRealtimeConnection')['useRealtimeConnection']>
    readonly useRealtimeEvent: UnwrapRef<typeof import('../composables/useRealtime')['useRealtimeEvent']>
    readonly useRealtimeModel: UnwrapRef<typeof import('../composables/useRealtime')['useRealtimeModel']>
    readonly useRealtimeNotification: UnwrapRef<typeof import('../composables/useRealtime')['useRealtimeNotification']>
    readonly useRealtimePresence: UnwrapRef<typeof import('../composables/useRealtime')['useRealtimePresence']>
    readonly useRemember: UnwrapRef<typeof import('@inertiajs/vue3')['useRemember']>
    readonly useResourceForm: UnwrapRef<typeof import('../composables/useResourceForm')['useResourceForm']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSchemaResourceForm: UnwrapRef<typeof import('../composables/useSchemaResourceForm')['useSchemaResourceForm']>
    readonly useServerDataTable: UnwrapRef<typeof import('../composables/useServerDataTable')['useServerDataTable']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToast: UnwrapRef<typeof import('../composables/useToast')['useToast']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}